update pdfcpu 0.4.0
henrixapp/pdfcomprezzor pull request #9
Opened 2023-03-01 01:40 UTC by christian-heusel

🚧 **Do not merge yet!** 🚧

To be fixed before merge/release:
 - [ ] fix usage of `api.Merge()` (I don't think I can do this):
   https://github.com/henrixapp/pdfcomprezzor/blob/8d4dce38599eb3457dc582b484da3996f1b0e2c1/main.go#L107
   ```
   GOOS=js GOARCH=wasm go build -o pdfcomprezzor.wasm                                                                                                1 ↵

   # github.com/henrixapp/pdfcomprezzor
   ./main.go:108:25: not enough arguments in call to api.Merge
           have ([]io.ReadSeeker, *bytes.Buffer, nil)
           want (string, []string, io.Writer, *model.Configuration)
   ```
- [ ] wait for PR https://github.com/pdfcpu/pdfcpu/pull/565 to be merged

2023-03-01 12:50 UTC, henrixapp commented
> fix usage of api.Merge() (I don't think I can do this):

The API was changed in https://github.com/pdfcpu/pdfcpu/commit/a86469b721d0592fd1b5a21bb46aa969ef9d7e74 , we will have to wait for a update on pdfcpu site.

2023-03-01 13:49 UTC, christian-heusel commented
> The API was changed in https://github.com/pdfcpu/pdfcpu/commit/a86469b721d0592fd1b5a21bb46aa969ef9d7e74 

I also noticed that and used `api.MergeOld()` but that got removed in the meantime aswell.

> we will have to wait for a update on pdfcpu site.

Can you report an issue about it and link it here? I unfortunately cant argue why things are the way they are or what exactly needs to be changed in order to get it running again 🤔

2023-03-01 20:42 UTC, christian-heusel commented
@henrixapp I think this is ready for merge, please review the changes, test and merge 👍🏻

2023-03-01 20:44 UTC, christian-heusel commented
Regarding the replace: We could ofc also wait for an upstream relase, but the last one took a year xD

2023-03-03 11:52 UTC, christian-heusel commented
Now I sadly have a found regression, with the pdf I sent you via messenger I get the following error on this branch: 
```
GEThttp://localhost:8082/favicon.ico
[HTTP/1.1 404 Not Found 0ms]

1 test.js:32:25
Worker said:  
message { target: Worker, isTrusted: true, data: {…}, origin: "", lastEventId: "", ports: Restricted, srcElement: Worker, currentTarget: Worker, eventPhase: 2, bubbles: false, … }
test.js:40:33
Worker said:  
message { target: Worker, isTrusted: true, data: {…}, origin: "", lastEventId: "", ports: Restricted, srcElement: Worker, currentTarget: Worker, eventPhase: 2, bubbles: false, … }
test.js:40:33
Worker said:  
message { target: Worker, isTrusted: true, data: {…}, origin: "", lastEventId: "", ports: Restricted, srcElement: Worker, currentTarget: Worker, eventPhase: 2, bubbles: false, … }
test.js:40:33
Worker said:  
message { target: Worker, isTrusted: true, data: {…}, origin: "", lastEventId: "", ports: Restricted, srcElement: Worker, currentTarget: Worker, eventPhase: 2, bubbles: false, … }
test.js:40:33
Worker said:  
message { target: Worker, isTrusted: true, data: {…}, origin: "", lastEventId: "", ports: Restricted, srcElement: Worker, currentTarget: Worker, eventPhase: 2, bubbles: false, … }
test.js:40:33
Worker said:  
message { target: Worker, isTrusted: true, data: {…}, origin: "", lastEventId: "", ports: Restricted, srcElement: Worker, currentTarget: Worker, eventPhase: 2, bubbles: false, … }
test.js:40:33
Worker said:  
message { target: Worker, isTrusted: true, data: {…}, origin: "", lastEventId: "", ports: Restricted, srcElement: Worker, currentTarget: Worker, eventPhase: 2, bubbles: false, … }
test.js:40:33
Worker said:  
message { target: Worker, isTrusted: true, data: {…}, origin: "", lastEventId: "", ports: Restricted, srcElement: Worker, currentTarget: Worker, eventPhase: 2, bubbles: false, … }
test.js:40:33
Worker said:  
message { target: Worker, isTrusted: true, data: {…}, origin: "", lastEventId: "", ports: Restricted, srcElement: Worker, currentTarget: Worker, eventPhase: 2, bubbles: false, … }
test.js:40:33
panic: runtime error: index out of range [9] with length 1 wasm_exec.js:22:14
<empty string> wasm_exec.js:22:14
goroutine 6 [running]: wasm_exec.js:22:14
main.glob..func1({{}, 0x0, 0x0}, {0x82c3e0, 0x2, 0x2}) wasm_exec.js:22:14
	/go/src/main.go:63 +0x126 wasm_exec.js:22:14
syscall/js.handleEvent() wasm_exec.js:22:14
	/usr/local/go/src/syscall/js/func.go:94 +0x26 wasm_exec.js:22:14
exit code: 2 wasm_exec.js:101:14
Error: Go program has already exited wasm_exec.js:536:11
```

2023-03-04 12:18 UTC, henrixapp requested changes
Please update to reflect map return type instead of array.

2023-03-04 12:18 UTC, henrixapp commented on main.go
> +		images, err := pdfcpu.ExtractPageImages(ctx, i, false)
ExtractPageImages returns a map instead of an array. Please update the lines below.

2023-03-04 12:18 UTC, henrixapp commented on main.go
>  				ctx.XRefTable.Table[objs[idx]].Object = *sd2
Now it is just `idx` instead of `objs[idx]`.

2023-03-04 12:18 UTC, henrixapp commented on main.go
>  				ctx.XRefTable.Table[objs[idx]].Object = *sd2
also update above.

2023-03-05 14:48 UTC, henrixapp approved these changes

2023-03-05 16:36 UTC, merged